version: '3.1'

services:
  pg:
    image: 'postgres:10.1-alpine'
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: 'fullstack'
      POSTGRES_PASSWORD: 'fullstack@123'
      POSTGRES_DB: 'fullstack_dev'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./services/pg/pgdata:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: 'chorss/docker-pgadmin4'
    ports:
      - 5050:5050
